---

- include: pb.init.make_clean.yaml
############################################################

- name: Create Analytics ,Mirror and Analyzer configuration for QFX5000 
  hosts: qfx5000
  connection: local
  gather_facts: no
  pre_tasks:
    - include_vars: "{{ topology_file }}"
  roles:
    - monitoring-analytics
    - monitoring-mirror-analyzer
    - monitoring-sflow

############################################################
- name: Create and apply configuration for Leaf QFX / L2
  hosts: leaf-qfx-l2
  connection: local
  gather_facts: no
  pre_tasks:
    - include_vars: "{{ topology_file }}"
  roles:
    - common
    - underlay-ospf
    - overlay-evpn-qfx-l2
    - overlay-evpn-access
    - build-config

############################################################
- name: Create and apply configuration for Leaf QFX / L3
  hosts: leaf-qfx-l3
  connection: local
  gather_facts: no
  pre_tasks:
    - include_vars: "{{ topology_file }}"
  roles:
    - common
    - underlay-ospf
    - overlay-evpn-qfx-l3
    - overlay-evpn-access
    - build-config

############################################################
- name: Create and apply configuration for Spines / MX
  hosts: spine-mx
  connection: local
  gather_facts: no
  pre_tasks:
    - include_vars: "{{ topology_file }}"
  roles:
    - common
    - underlay-ospf
    - overlay-evpn-mx-l3
    - build-config

############################################################
- name: Create and apply configuration for Spines / QFX
  hosts: spine-qfx
  connection: local
  gather_facts: no
  pre_tasks:
    - include_vars: "{{ topology_file }}"
  roles:
    - common
    - underlay-ospf
    - overlay-evpn-qfx-l3
    - build-config

############################################################
- name: Create and apply configuration for Fabric
  hosts: fabric
  connection: local
  gather_facts: no
  pre_tasks:
    - include_vars: "{{ topology_file }}"
  roles:
    - common
    - underlay-ospf
    - build-config

###############################################################
- name: Git commit
  hosts: localhost
  tasks:
    - shell: git add .
    - shell: git commit -m "{{ comment }}"
    - shell: git push -u origin master
